name: Simple Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem
          
      - name: Deploy
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem \
            index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/